name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Android SDK
      run: |
        mkdir -p $ANDROID_HOME
        cd $ANDROID_HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        rm -rf cmdline-tools/latest/cmdline-tools
        echo $ANDROID_HOME/cmdline-tools/latest/bin >> $GITHUB_PATH
        echo $ANDROID_HOME/platform-tools >> $GITHUB_PATH
        echo $ANDROID_HOME/build-tools >> $GITHUB_PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      env:
        ANDROID_HOME: /usr/local/android-sdk
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      env:
        ANDROID_HOME: /usr/local/android-sdk
      
    - name: Build APK
      run: ./gradlew assembleRelease
      env:
        ANDROID_HOME: /usr/local/android-sdk
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk 